theme: jekyll-theme-time-machine
title: Welcome to Amanda Kiefer's Portfolio
description: I am a Computer Science student at Southern New Hampshire University. The purpose of this page is to highlight a few select projects I have developed while completing my degree.
