theme: jekyll-theme-time-machine
title: Welcome to Amanda Kiefer's Portfolio
description: I am a recent Computer Science graduate from Southern New Hampshire University. The purpose of this page is to highlight a few select projects I have developed while completing my degree.
